spring:
  datasource:
    url: jdbc:h2:mem:demo_db
    username: as
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: H2
    properties:
      javax.persistence.create-database-schemas: true
logging:
  level:
    root: info
    org.jooq: debug